### ISSUE TITLE
Changing QuestionText on Show

### ISSUE THREAD

**Issue by arkytn** [invetek/jquery-confirmon#13]
I have a list of links that  need confirmations on and each needs different text for that particular links popup. I tried using the new onShow function but can't seem figure out how to change the questionText

Ideas?

**Comment by invetek** [comment]
Let's say you have these links. Add the questions texts as data attributes.
```html
<a class="confirm-link" href="/page-1" data-confirmon-text="Are you sure you want to go to page 1?">Page 1</a>
<a class="confirm-link" href="/page-2" data-confirmon-text="Are you sure you want to go to page 2?">Page 2</a>
<a class="confirm-link" href="/page-3" data-confirmon-text="Are you sure you want to go to page 3?">Page 3</a>
```

In the javascript you can iterate over these links while using the data attribute.
```javascript
$('.confirm-link').each(function(){
  myQuestion = $(this).data('confirmon-text');
  $(this).confirmOn({
     questionText: myQuestion,
     textYes: 'Yes, I\'m sure',
     textNo: 'No, I\'m not sure'
     },'click', function(e, confirmed) {
        if(confirmed) doSomething();
     });
});
```

Hope this helps!

**Comment by arkytn** [comment]
That would work.

I came up with another work around that is more straight forward.

I added a this, and $element to the onShow call

 doShow = $element.data('confirmon').options.onShow.call(this, $element);

Now in onShow parameter I can do this without iterating explicitly

  $('.em-event-single-delete').confirmOn({
   textYes: 'Delete',
   textNo: 'Cancel',
   onShow: function( that ){
    $element = $(that);
    $element.data('confirmon').options.questionText =
    '<p>Delete<br/>'
    + $element.data('title')
    + '<br/><i>This cannot be undone</i><br/>'
    + 'Are you sure?'
    + '</p>';
   }
  }, 'click', function(e, confirmed){
   if(confirmed) { // Clicked yes
    window.location.href = $(this).prop('href');
   } else { // Clicked no
   }
  });

Thanks for the other idea.



On Thu, Apr 2, 2015 at 3:09 AM, Loran Kloeze <notifications@github.com>
wrote:

> Let's say you have these links. Add the questions texts as data attributes.
>
> <a class="confirm-link" href="/page-1" data-confirmon-text="Are you sure you want to go to page 1?">Page 1</a>
> <a class="confirm-link" href="/page-2" data-confirmon-text="Are you sure you want to go to page 2?">Page 2</a>
> <a class="confirm-link" href="/page-3" data-confirmon-text="Are you sure you want to go to page 3?">Page 3</a>
>
> In the javascript you can iterate over these links while using the data
> attribute.
>
> $('.confirm-link').each(function(){
>   myQuestion = $(this).data('confirmon-text');
>   $(this).confirmOn({
>      questionText: myQuestion,
>      textYes: 'Yes, I\'m sure',
>      textNo: 'No, I\'m not sure'
>      },'click', function(e, confirmed) {
>         if(confirmed) doSomething();
>      });
> });
>
> Hope this helps!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/invetek/jquery-confirmon/issues/13#issuecomment-88783363>
> .
>



-- 
Arnold Bailey | WebWrights | support@webwrights.com

**Comment by invetek** [comment]
That works too, it looks more like a template that way. Thanks for your feedback!
